Split locals and args
b9org/b9 pull request #199
Opened 2018-06-08 21:45 UTC by nbhuiyan

Signed-off-by: Nazim Uddin Bhuiyan <nazimudd@ualberta.ca>

2018-06-13 14:27 UTC, rwy7 requested changes
IIUC, there are some issues with arguments and parameters being overlayed on the same stack slots.

On top of that, I would really like to get our terminology consistent, and I think this PR is a good place to start:

1) parameters vs arguments: I suggest going with param or parameter everywhere. It's closer to the JS standard and esprima terminology. parameter used to be an slightly overloaded term, but instruction parameters were renamed to immediates.

2) vars vs locals vs registers: suggesting we go with local. Originally I was pushing "register", but that word is probably confusing.

2018-06-13 14:27 UTC, rwy7 commented on b9/src/ExecutionContext.cpp
> +void ExecutionContext::doPushFromArg(StackElement *args, Immediate offset){
formatting

2018-06-13 14:27 UTC, rwy7 commented on b9/src/ExecutionContext.cpp
> +void ExecutionContext::doPopIntoArg(StackElement *args, Immediate offset){
formatting

2018-06-13 14:27 UTC, rwy7 commented on b9/src/ExecutionContext.cpp
> +        doPopIntoVar(args, instructionPointer->immediate());
*sigh* what a silly mistake 🐱
thanks for fixing.

2018-06-13 14:27 UTC, rwy0717 commented on b9/include/b9/instructions.hpp
> +
I know this is a lot of tedious work, but can we have the push/pop from arg come right after (or before) the var instructions?

2018-06-13 14:27 UTC, rwy0717 commented on b9/src/MethodBuilder.cpp
> +    case OpCode::POP_INTO_ARG:
OK, looking at the frontend, the parameters and locals each use a different symbol table. This means that args and params are indexed differently; arg[0] is not the same as local[0]. But here, it looks like arg[0] and local[0] are aliased. Is this a bug? There's the same issue in the interpreter.

2018-06-13 14:27 UTC, rwy0717 commented on b9run/main.cpp
> +  const char* mainFunction = "b9main";
why did we change this?

2018-06-25 21:33 UTC, nbhuiyan commented
@rwy0717 Ready for another review. There is a merge conflict that I will fix after the changes have been approved.

2018-06-26 14:37 UTC, rwy7 commented on b9/include/b9/instructions.hpp
> +    case OpCode::POP_INTO_LOCAL:
Missing push/pop param

2018-06-26 14:39 UTC, rwy0717 commented on b9/include/b9/instructions.hpp
> +    case OpCode::POP_INTO_LOCAL:
nevermind... how did I miss it :p

2018-06-26 14:40 UTC, nbhuiyan commented on b9/include/b9/instructions.hpp
> +    case OpCode::POP_INTO_LOCAL:
I missed it too at first and only recently pushed that :P

2018-06-26 14:41 UTC, rwy7 approved these changes

2018-06-26 16:10 UTC, nbhuiyan commented
@rwy0717 The merge conflicts have been fixed, and the CI build has passed. I think it is ready to be merged.

2018-06-26 17:56 UTC, rwy0717 commented
LGTM. Now that we differentiate between locals and arguments, we should take another look at how the JIT feature flags (passparam, lazy-vm-state) affect how locals and parameters behave. Thanks @nbhuiyan. closes #154.

2018-06-26 17:57 UTC, merged